### ISSUE TITLE
Incorrect colour of errors when running vim terminal

### ISSUE THREAD

**Issue by matteematt** [habamax/vim-gruvbit#3]
Sorry if this is the wrong place to ask, feel free to close this issue if so.

When using the vim terminal with the gruvbit colour schemes the error colours are yellow rather than orange. Is this something wrong with the highlighting groups of this colour scheme, or do you think I have something set up wrong?

For example:
Error code 2 returned in my zsh prompt
![Error code 2 returned in my zsh prompt](https://user-images.githubusercontent.com/43502076/105745764-8c33a680-5f36-11eb-8600-14601f380c20.png)

Error in GHCI
![Error in GHCI](https://user-images.githubusercontent.com/43502076/105745803-95bd0e80-5f36-11eb-942a-61db65bfe71c.png)

Error code 2 returned in my zsh prompt when viewed inside of vim terminal
![Error code 2 returned in my zsh prompt when viewed inside of vim terminal](https://user-images.githubusercontent.com/43502076/105745871-a8374800-5f36-11eb-844f-a3a081636f03.png)

Error in GHCI when viewed inside of vim terminal:
![Error in GHCI when viewed inside of vim terminal](https://user-images.githubusercontent.com/43502076/105745928-b71dfa80-5f36-11eb-80b9-041418e790e0.png)

**Comment by habamax** [comment]
it is probably wrong mapping of the red color in the colorscheme, will check it

**Comment by matteematt** [comment]
I have noticed some more differences in the colour. When running tests in `sbt` I get an output that looks like this in my normal terminal:
![image](https://user-images.githubusercontent.com/43502076/105908055-ad22f700-601d-11eb-89bf-23ef8b3e3dba.png)

But the same output has a different colour when viewed via the vim terminal:
![image](https://user-images.githubusercontent.com/43502076/105908090-b90eb900-601d-11eb-8331-22d33f733547.png)

**Comment by habamax** [comment]
Just to clarify some things:

1. I don't know what colors your terminal uses, probably some variant of `gruvbox` palette
2. in vim colorschemes one can setup built-in terminal palette which should be aligned with the colors of said colorschemes

Thus, even if I "fix" red color and some other colors, I would fix it for the built-in terminal palette which has nothing to do with external terminal palette.

**Comment by habamax** [comment]
I have remapped some of the colors, thus red should be red. Nevertheless it would not be the same colors as you have in your host terminal.

**Comment by matteematt** [comment]
I have just given it a go and that is much better! I am not fussed about the colours being exactly the same, more that they were just reflecting the general colours you'd expect (e.g. errors show as red)

Thanks for taking the time to implement this, it is much appreciated!
