### ISSUE TITLE
Neovim isn't loading theme the first time

### ISSUE THREAD

**Issue by diegoulloao** [habamax/vim-gruvbit#4]
For some reason nvim isn't loading the theme when I open it. I have to reload my configuration file `source $MYVIMRC` in order to see the theme applied.

```
E185: Cannot find color scheme 'gruvbit'
```

Only happens with this theme specifically, I tried others.

```
NVIM v0.6.1
Build type: Release
macOs Monterrey 12.1
```

**Comment by habamax** [comment]
Probably depends on how you did install it?

If it is in /pack/... folder then it should work, if you use vim-plug, then `colorscheme gruvbit` should be after all vim-plug boilerplate etc.

**Comment by diegoulloao** [comment]
> Probably depends on how you did install it?
> 
> If it is in /pack/... folder then it should work, if you use vim-plug, then `colorscheme gruvbit` should be after all vim-plug boilerplate etc.

I installed it using vim-plug:

```vimscript
call plug#begin('~/.vim/plugged')
  Plug 'habamax/vim-gruvbit'
call plug#end()
```

I have `colorscheme` instruction after vim-plug section.

Looks like a "timing" issue.

**Comment by diegoulloao** [comment]
I moved the instruction at the last line of my `.vimrc` file and now it's working. It's strange because only happened with this scheme. But anyways, problem solved.

Sorry for bother you and thank you very much for the quick response.

Hope this be useful for anyone who have the same issue.
